### ISSUE TITLE
Create a Venue model in mongoose for caching

### ISSUE THREAD

**Issue by pete-ryu** [nyczmagix/nomz#4]
https://developer.foursquare.com/docs/responses/venue

name, address, lat, lng, category (cuisine), hours, menu, price (how expensive), rating, etc.

**Comment by ajstocchetti** [comment]
As per forsquare, we shouldnt just steal their venue info. we should query them every time
https://developer.foursquare.com/overview/venues#rules

**Comment by pete-ryu** [comment]
Updated this to be an "enhancement" instead
